
[colors.primary]
foreground = "#d4be98"
background = "#161819"
dim_foreground = "#d4be98"
bright_foreground = "#4c5357"

[colors.cursor]
text = "#161819"
cursor = "#d4be98"

[colors.vi_mode_cursor]
text = "#161819"
cursor = "#d4be98"

[colors.selection]
text = "#161819"
background = "#d4be98"

[colors.normal]
black = "#161819"
red = "#e96861"
green = "#a9b665"
yellow = "#d8a657"
blue = "#658b83"
magenta = "#d3869b"
cyan = "#89b482"
white = "#d4be98"

[colors.bright]
black = "#4c5357"
red = "#e96861"
green = "#a9b665"
yellow = "#d8a657"
blue = "#658b83"
magenta = "#d3869b"
cyan = "#89b482"
white = "#d4be98"

[colors.dim]
black = "#161819"
red = "#e96861"
green = "#a9b665"
yellow = "#d8a657"
blue = "#658b83"
magenta = "#d3869b"
cyan = "#89b482"
white = "#d4be98"



[env]
SHELL = "/bin/zsh"
TERM = "alacritty"

[font]
size = 10

[font.bold]
family = "Maple Mono NF"
style = "Bold"

[font.bold_italic]
family = "Maple Mono NF"
style = "Bold Italic"

[font.italic]
family = "Maple Mono NF"
style = "Italic"

[font.normal]
family = "Maple Mono NF"
style = "Medium"

[font.offset]
x = 1