#!/usr/bin/env bash
RASI="$HOME/.config/rofi/config.rasi"

SELECTED=$(ls ~/dotfiles/ | rofi -dmenu -config $RASI)
SELECTED_DIR=~/dotfiles/$SELECTED


echo $SELECTED_DIR

if [[ -n "$SELECTED" ]]; then
/bin/rm ~/.config/waybar & /bin/rm ~/.config/sway & /bin/rm ~/.config/rofi & /bin/rm ~/.config/alacritty & /bin/rm ~/.config/starship.toml ; ln -s $SELECTED_DIR/waybar ~/.config/waybar & ln -s $SELECTED_DIR/sway ~/.config/sway & ln -s $SELECTED_DIR/rofi ~/.config/rofi & ln -s $SELECTED_DIR/alacritty ~/.config/alacritty &  ln -s $SELECTED_DIR/starship.toml ~/.config/starship.toml ; swaymsg reload & pkill waybar & waybar  &  $SELECTED_DIR/gtk.sh 
fi

