"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](bg:rose fg:rose)\
$os\
$username\
[](bg:pine fg:rose)\
$directory\
[](fg:pine bg:iris)\
$git_branch\
$git_status\
[](fg:iris bg:overlay)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$character"""





palette = 'rose-pine-moon'

[palettes.rose-pine]
base = '#191724'
surface = '#1f1d2e'
overlay = '#26233a'
muted = '#6e6a86'
subtle = '#908caa'
text = '#e0def4'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'
highlight_low = '#21202e'
highlight_med = '#403d52'
highlight_high = '#524f67'

[palettes.rose-pine-moon]
base = '#232136'
surface = '#2a273f'
overlay = '#393552'
muted = '#6e6a86'
subtle = '#908caa'
text = '#e0def4'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ea9a97'
pine = '#3e8fb0'
foam = '#9ccfd8'
iris = '#c4a7e7'
highlight_low = '#2a283e'
highlight_med = '#44415a'
highlight_high = '#56526e'

[palettes.rose-pine-dawn]
base = '#faf4ed'
surface = '#fffaf3'
overlay = '#f2e9e1'
muted = '#9893a5'
subtle = '#797593'
text = '#575279'
love = '#b4637a'
gold = '#ea9d34'
rose = '#d7827e'
pine = '#286983'
foam = '#56949f'
iris = '#907aa9'
highlight_low = '#f4ede8'
highlight_med = '#dfdad9'
highlight_high = '#cecacd'

[os]
disabled = false
style = "bg:rose fg:overlay"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:rose fg:overlay"
style_root = "bg:rose fg:overlay"
format = '[ $user ]($style)'

[directory]
style = "fg:text bg:pine"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:iris"
format = '[[ $symbol $branch ](fg:base bg:iris)]($style)'

[git_status]
style = "bg:iris"
format = '[[($all_status$ahead_behind )](fg:base bg:iris)]($style)'

[nodejs]
symbol = ""
style = "bg:overlay"
format = '[[ $symbol( $version) ](fg:rose bg:overlay)]($style)'

[c]
symbol = " "
style = "bg:overlay"
format = '[[ $symbol( $version) ](fg:rose bg:overlay)]($style)'

[rust]
symbol = ""
style = "bg:overlay"
format = '[[ $symbol( $version) ](fg:rose bg:overlay)]($style)'

[golang]
symbol = ""
style = "bg:overlay"
format = '[[ $symbol( $version) ](fg:rose bg:overlay)]($style)'

[php]
symbol = ""
style = "bg:overlay"
format = '[[ $symbol( $version) ](fg:rose bg:overlay)]($style)'

[java]
symbol = " "
style = "bg:overlay"
format = '[[ $symbol( $version) ](fg:rose bg:overlay)]($style)'

[kotlin]
symbol = ""
style = "bg:overlay"
format = '[[ $symbol( $version) ](fg:rose bg:overlay)]($style)'

[haskell]
symbol = ""
style = "bg:overlay"
format = '[[ $symbol( $version) ](fg:rose bg:overlay)]($style)'

[python]
symbol = ""
style = "bg:overlay"
format = '[[ $symbol( $version) ($virtualenv)](fg:rose bg:overlay)]($style)'

[docker_context]
symbol = ""
style = "bg:iris"
format = '[[ $symbol( $context) ](fg:text bg:iris)]($style)'

[conda]
style = "bg:iris"
format = '[[ $symbol( $environment) ](fg:text bg:iris)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:gold"
format = '[[  $time ](fg:text bg:overlay)]($style)'

[line_break]
disabled = false


[character]
success_symbol = "[](overlay)"
error_symbol = "[](love)"


